# Generated by Django 5.1.3 on 2025-04-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blogcategorymodel_countermodel_customerfeedbackmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategorymodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
