# Generated by Django 5.1.3 on 2025-04-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_projectcategorymodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategorymodel',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
