# Generated by Django 5.1.3 on 2025-04-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_blogmodel_author_alter_blogmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='author',
        ),
    ]
