# Generated by Django 5.1.3 on 2025-04-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blogmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='author',
        ),
    ]
