# Generated by Django 5.1.3 on 2025-04-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='subject',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
