# Generated by Django 5.1.3 on 2025-04-10 18:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_contactmodel_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteammembermodel',
            name='certificate_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ourteammembermodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourteammembermodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CertificateGalleryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificate')),
                ('ourteam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ourteammembermodel')),
            ],
        ),
    ]
