# Generated by Django 5.1.3 on 2025-04-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ourteammembermodel_certificate_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificategallerymodel',
            name='ourteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='app.ourteammembermodel'),
        ),
    ]
