# Generated by Django 5.1.3 on 2025-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_certificategallerymodel_ourteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
