# Generated by Django 5.1.3 on 2025-04-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_ourservicelistmodel_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourservicelistmodel',
            old_name='image',
            new_name='icon_image',
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='image_inner',
            field=models.ImageField(blank=True, null=True, upload_to='OurService'),
        ),
    ]
