# Generated by Django 5.1.3 on 2025-04-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_image_ourservicelistmodel_icon_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='clients_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
