# Generated by Django 5.1.3 on 2025-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_projectmodel_clients_name_projectmodel_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='viber',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
