# Generated by Django 5.1.3 on 2025-04-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_projectmodel_facebook_projectmodel_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_category', to='app.projectcategorymodel'),
        ),
    ]
