# Generated by Django 5.1.3 on 2025-04-12 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_projectmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='clients_name',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='viber',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='app.projectcategorymodel'),
        ),
    ]
