# Generated by Django 5.1.3 on 2025-04-12 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_projectmodel_clients_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServiceListCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_category', to='app.ourservicelistcategory'),
        ),
    ]
