# Generated by Django 5.1.3 on 2025-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_ourservicelistcategory_ourservicelistmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='service_detail_icon_1',
            field=models.ImageField(blank=True, null=True, upload_to='OurService'),
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='service_detail_icon_1_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='service_detail_icon_2',
            field=models.ImageField(blank=True, null=True, upload_to='Ourservice'),
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='service_detail_icon_2_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='service_detail_icon_3',
            field=models.ImageField(blank=True, null=True, upload_to='Ourservice'),
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='service_detail_icon_3_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
