# Generated by Django 5.1.3 on 2025-04-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_ourservicelistmodel_service_detail_icon_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='accrodion_content_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='accrodion_content_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='accrodion_content_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='accrodion_title_1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='accrodion_title_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='accrodion_title_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
