# Generated by Django 5.1.3 on 2025-04-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_ourservicelistmodel_accrodion_content_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='service_detail_icon_title_1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='service_detail_icon_title_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='service_detail_icon_title_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
