# Generated by Django 5.1.3 on 2025-04-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_ourservicelistmodel_service_detail_icon_title_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservicelistmodel',
            name='service_detail_icon_title_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ourservicelistmodel',
            name='service_detail_icon_title_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
