# Generated by Django 5.1.3 on 2025-04-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_ourservicelistmodel_service_detail_icon_title_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='benefits_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='benefits_image',
            field=models.ImageField(blank=True, null=True, upload_to='Ourservice'),
        ),
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='benefits_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
