# Generated by Django 5.1.3 on 2025-04-13 10:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_aboutmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslidermodel',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
