# Generated by Django 5.1.3 on 2025-04-13 11:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_homeslidermodel_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
