# Generated by Django 5.1.3 on 2025-04-13 11:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_newslettermode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslidermodel',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
