# Generated by Django 5.1.3 on 2025-04-13 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_homeslidermodel_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccrodionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accrodion_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('accrodion_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ourservicelistmodel',
            name='accrodion_content_1',
        ),
        migrations.RemoveField(
            model_name='ourservicelistmodel',
            name='accrodion_content_2',
        ),
        migrations.RemoveField(
            model_name='ourservicelistmodel',
            name='accrodion_content_3',
        ),
        migrations.RemoveField(
            model_name='ourservicelistmodel',
            name='accrodion_title_1',
        ),
        migrations.RemoveField(
            model_name='ourservicelistmodel',
            name='accrodion_title_2',
        ),
        migrations.RemoveField(
            model_name='ourservicelistmodel',
            name='accrodion_title_3',
        ),
    ]
