# Generated by Django 5.1.3 on 2025-04-13 12:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_accrodionmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslidermodel',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
