# Generated by Django 5.1.3 on 2025-04-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_aboutmodel_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='pj_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
