# Generated by Django 5.1.3 on 2025-04-13 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_projectmodel_pj_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeamProgressModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('progress_value', models.CharField(blank=True, max_length=200, null=True)),
                ('ourteam_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_value', to='app.ourteammembermodel')),
            ],
        ),
    ]
