# Generated by Django 5.1.3 on 2025-04-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_whychooseusmodel_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservicelistmodel',
            name='points',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
