# Generated by Django 5.1.3 on 2025-04-30 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_ourservicelistmodel_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrodionmodel',
            name='accrodion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accrodion_value', to='app.ourservicelistmodel'),
        ),
    ]
