# Generated by Django 5.1.3 on 2025-04-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_accrodionmodel_accrodion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteammembermodel',
            name='viber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
