# Generated by Django 5.1.3 on 2025-04-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_ourteammembermodel_viber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteammembermodel',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
